# Generated by Django 3.2.3 on 2021-06-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('user_name', models.TextField()),
                ('user_pw', models.TextField()),
                ('user_email', models.EmailField(max_length=254, verbose_name='user_email')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='register_date')),
            ],
        ),
    ]
