# Generated by Django 3.2.2 on 2021-06-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_id',
        ),
    ]
