# Generated by Django 3.2.2 on 2021-06-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Group_info',
        #     fields=[
        #         ('group_seq', models.AutoField(primary_key=True, serialize=False)),
        #         ('name', models.TextField()),
        #         ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
        #         ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='account.user_info')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Suggestion',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('topic', models.CharField(help_text='제목', max_length=80, null=True)),
        #         ('other_selection', models.BooleanField(default=True)),
        #         ('no_selection', models.BooleanField(default=True)),
        #         ('group_sequence', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, related_name='group_seq2', to='opinion.group_info')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Selection',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('selection_content', models.CharField(max_length=100)),
        #         ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='opinion.suggestion')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Response',
        #     fields=[
        #         ('response_seq', models.AutoField(primary_key=True, serialize=False)),
        #         ('content', models.TextField(help_text='이유 및 의견')),
        #         ('selection_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinion.selection')),
        #         ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinion.suggestion')),
        #         ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Membership',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('join_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
        #         ('auth', models.CharField(default=None, max_length=3, null=True)),
        #         ('group', models.ForeignKey(db_column='group_seq', on_delete=django.db.models.deletion.CASCADE, related_name='Membership', to='opinion.group_info')),
        #         ('user', models.ForeignKey(db_column='user_seq', on_delete=django.db.models.deletion.CASCADE, related_name='Membership', to='account.user_info')),
        #     ],
        # ),
    ]
